### PR TITLE
Minor improvements to documentation for hacking HaLVM

### PR DESCRIPTION
**Pull request by mspaulding06**
Just made a few very small improvements to the documentation.  For instance, adding information on Fedora 26 (which is able to compile HaLVM) and updating commands and package information to make the build process a little smoother.

### CODE REVIEW

**Comment by izgzhen** [comment]
Looks good overall. But I would suggest to make sure that the changed portion still applies to older versions, since it is said so. Or else, provide lines like this:

```bash
$ ifconfig # if Fedora 22, 23, 24

$ ip a # if Fedora 25, 26
```

What do you think?

**Comment by acw** [comment]
w00t! Thanks!

**Comment by mspaulding06** [comment]
@izgzhen I think that just including `ip a` should be fine if you are okay with that.  The `iproute` package is included in Fedora back to release 22 and should be used where possible since `ifconfig` is deprecated.

**Comment by mspaulding06** [comment]
@acw Did you intend to close the PR without merging?

**Comment by acw** [comment]
Ah-hah! You solved my brain teaser! Congrats!

**Pull request merged**
